project_name: MCP Selenium Server
version: 0.1.0
deployment_mode: docker # one of: docker, kubernetes (DeploymentMode enum values)
api_v1_str: /api/v1
api_token: CHANGE_ME
allowed_origins:
  - http://localhost:8000

selenium_grid:
  max_browser_instances: 10
  se_node_max_sessions: 1
  user: user
  password: CHANGE_ME
  vnc_password: CHANGE_ME
  vnc_view_only: false
  vnc_port: 7900
  browser_configs:
    chrome:
      image: selenium/node-chrome:4.18.1
      port: 4444
      resources:
        memory: "1G"
        cpu: "0.5"
    firefox:
      image: selenium/node-firefox:4.18.1
      port: 4444
      resources:
        memory: "1G"
        cpu: "0.5"
    edge:
      image: selenium/node-edge:4.18.1
      port: 4444
      resources:
        memory: "1G"
        cpu: "0.5"
kubernetes:
  kubeconfig: ~/.kube/config-local-k3s
  context: k3s-selenium-grid
  namespace: selenium-grid-dev
  selenium_grid_service_name: selenium-grid
  retry_delay_seconds: 2
  max_retries: 5
