development: true
api_token: CHANGE_ME
selenium_hub_port: 4444
selenium_node_max_sessions: 1
selenium_hub_user: user
selenium_hub_password: CHANGE_ME
max_browser_instances: 5
deployment_mode: docker # or kubernetes
k8s_namespace: selenium-grid-dev
allowed_origins:
  - http://localhost:8000
browser_configs:
  chrome:
    image: selenium/node-chrome:4.18.1
    port: 4444
    resources:
      memory: "2G"
      cpu: "1"
  firefox:
    image: selenium/node-firefox:4.18.1
    port: 4444
    resources:
      memory: "2G"
      cpu: "1"
  edge:
    image: selenium/node-edge:4.18.1
    port: 4444
    resources:
      memory: "2G"
      cpu: "1"
