name: Setup Python and uv

description: |
  Composite action to set up Python, install uv, and install dependencies for MCP Selenium Grid.

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.13"
  install-dev:
    description: "Install dev and test dependencies (true/false)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      run: pip install uv
      shell: bash
    - name: Install dependencies
      run: |
        if [ "${{ inputs.install-dev }}" = "true" ]; then
          uv pip install -e ".[dev,test]"
        else
          uv pip install .
        fi
      shell: bash
