name: Release Python Package and Docker Image

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Whether to publish the Python package and Docker image (true/false)'
        required: false
        default: 'false'

# This workflow is intended to be run manually for releases.
# It does not depend on CI passing, but it is recommended to only run after CI passes.

jobs:
  build-python-package:
    uses: ./.github/workflows/2.1_build-python-package.yml
    with:
      publish: ${{ github.event.inputs.publish }}
      upload-github-release: 'false'
    secrets: inherit

  build-docker-image:
    uses: ./.github/workflows/2.2_build-docker-image.yml
    with:
      image-name: ghcr.io/${{ github.repository }}:${{ needs.build-python-package.outputs.version }}
      extra-tag: ghcr.io/${{ github.repository }}:latest
      context: .
      dockerfile: src/deployment/docker/Dockerfile
      push: ${{ github.event.inputs.publish }}
    secrets: inherit
    needs: build-python-package

  create-github-release:
    if: ${{ github.event.inputs.publish == 'true' && needs.build-python-package.result == 'success' && needs.build-docker-image.result == 'success' }}
    uses: ./.github/workflows/2.3_create-github-release.yml
    with:
      version: ${{ needs.build-python-package.outputs.version }}
      docker-image: ghcr.io/${{ github.repository }}:${{ needs.build-python-package.outputs.version }}
      python-package: ${{ needs.build-python-package.outputs.version }}
    secrets: inherit
    needs: [build-python-package, build-docker-image]
