name: Build Docker Image

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Docker image name (including tag)'
        required: true
        type: string
      context:
        description: 'Build context path'
        required: false
        default: .
        type: string
      dockerfile:
        description: 'Dockerfile path'
        required: false
        default: Dockerfile
        type: string
      push:
        description: 'Whether to push the image (true/false)'
        required: false
        default: 'false'
        type: string

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Build Docker image
        run: |
          docker build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache -t ${{ inputs.image-name }} -f ${{ inputs.dockerfile }} ${{ inputs.context }}
      # Optionally push (not implemented here)
